version: '3'
networks:
  bnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_SUBNET}

services:
  mcl:
    build: ./mcl/
    container_name: b_mcl
    ports:
      - "${MCL_PORT}:${MCL_MAPPING_PORT}"
    volumes:
      - ./mcl/config.json:/data/mirai/config.json
      - ./mcl/plugins/:/data/mirai/plugins:rw
      - ./mcl/config/:/data/mirai/config/:rw
      - ./mcl/bots/:/data/mirai/bots/:rw
      - ./mcl/data/:/data/mirai/data/:rw
      - ${IMAGE_PATH}:${IMAGE_PATH}
    extra_hosts:
      - "${ADAPTOR_URL}:${MCL_HOST_IP}"
    networks:
      bnet:
        ipv4_address: ${MCL_HOST_IP}