version: '3'

networks:
  bnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_SUBNET}

services:
  mcl:
    build: ./mcl/
    container_name: m_mcl
    image: blankqwq/mirai-mcl:latest
    volumes:
      - ./mcl/config.json:/data/mirai/config.json
      - ./mcl/plugins/:/data/mirai/plugins:rw
      - ./mcl/config/:/data/mirai/config/:rw
      - ./mcl/bots/:/data/mirai/bots/:rw
      - ./mcl/data/:/data/mirai/data/:rw
      - ${CODE_DIR_NAME}:/data/www
    links:
      - php
    networks:
      bnet:
        ipv4_address: ${MCL_HOST_IP}
  php:
    build: 
      context: ./php/
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: m_php
    image: blankqwq/mirai-php:${PHP_VERSION}
    volumes:
      - ${CODE_DIR_NAME}/:/data/www:rw
      - ./php/logs/:/var/logs/
      - ./php/conf/php.ini:/etc/php.ini:ro
      - ./php/conf/php-fpm.conf:/etc/php-fpm.conf:ro
      - ./php/conf/xdebug.ini:/etc/xdebug.ini:rw
      - ./php/supervisor/:/etc/supervisord.d/
      - ./php/nginx/:/etc/nginx/vhost/
      - ./php/sys/nginx.conf:/etc/nginx/nginx.conf
      - ./php/sys/phpcgi.conf:/etc/nginx/fastcgi.conf
    links:
      - redis
    networks:
      bnet:
        ipv4_address: ${PHP_FPM_IP}
  redis:
    build: 
      context: ./redis/
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
    container_name: m_redis
    image: blankqwq/blnmp-redis
    volumes:
      - ./redis/conf/:/etc/redis/:ro
      - ./redis/data/:/var/run/redis/:rw
      - ./redis/logs/:/var/logs/:rw
    networks:
      bnet:
        ipv4_address: ${REDIS_IP}