adapters: 
  - http
debug: false
enableVerify: true
verifyKey: INITKEYkritaKC1
singleMode: false
cacheSize: 4096
adapterSettings: 
  webhook:
      ## 回调(上报)地址
      destinations: 
      - 'php:80/qq'
      ## 额外自定义请求头
      extraHeaders:
        A: B
