adapters: 
  - http
  - webhook
debug: true
enableVerify: true
verifyKey: INITKEYkritaKC1
singleMode: false
cacheSize: 4096
adapterSettings: 
  http:
    host: 0.0.0.0
    port: 8082
    cors: ["*"]
    unreadQueueMaxSize: 100
  webhook:
    destinations: 
      - 'http://php/api/qq'
    extraHeaders:
      A: B
      header2: value2
